name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código
    - name: Checkout code
      uses: actions/checkout@v2

    # Configuração da chave SSH
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 152.67.61.112 >> ~/.ssh/known_hosts  # Adiciona o host ao arquivo known_hosts para evitar prompts de confirmação

    # Executar o script no servidor via SSH com permissões elevadas
    - name: SSH into server and run script with sudo
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@152.67.61.112 "sudo -u ubuntu bash /home/ubuntu/executa.sh"
